
[general]

[s3]
  bucketname = "tap1"
  conversationspath = "conversations"

[mqtt]
  broker = "tcp://3.8.78.60:1883"
  keepalive = 20
  password = ""
  timeout = 30
  username = ""


[sqs]
  inboxURL = "https://sqs.eu-west-2.amazonaws.com/049513327431/TA-inbox"
  outboxURL = "https://sqs.eu-west-2.amazonaws.com/049513327431/TA-outbox"


[log]
  fileout = false
  level = "info"
  logfilepath = "/tmp"
  stdout = true
  jsonformat = false

